static const char black[]       = "#1e222a";
static const char gray2[]       = "#2e323a"; // unfocused window border
static const char gray3[]       = "#545862";
static const char gray4[]       = "#6d8dad";
static const char blue[]        = "#81A1C1";  // focused window border
static const char green[]       = "#7EC7A2";
static const char red[]         = "#e06c75";
static const char orange[]      = "#caaa6a";
static const char yellow[]      = "#EBCB8B";
static const char pink[]        = "#c678dd";
static const char purple0[]     = "#9266d7";
static const char purple1[]     = "#976bdc";
static const char purple2[]     = "#9c70e1";
static const char purple3[]     = "#a175e6";
static const char purple4[]     = "#a67aeb";
static const char purple5[]     = "#ab7ff0";
static const char purple6[]     = "#b084f5";
static const char purple7[]     = "#b589fa";
static const char purple8[]     = "#ba8eff";
static const char col_borderbar[]  = "#1e222a"; // inner border
