/* static const char black[]       = "#1e222a"; */
/* static const char black[]       = "#181c24"; */
static const char black[]       = "#171b1f";
static const char gray2[]       = "#2e323a"; // unfocused window border
static const char gray3[]       = "#545862";
static const char gray4[]       = "#6d8dad";
static const char blue[]        = "#81a1c1";  // focused window border
static const char green[]       = "#7ec7a2";
static const char red[]         = "#e06c75";
static const char orange[]      = "#caaa6a";
static const char yellow[]      = "#ebcb8b";
static const char pink[]        = "#c678dd";
static const char purple0[]     = "#9266d7";
static const char purple1[]     = "#9266d7";
static const char purple2[]     = "#9266d7";
static const char purple3[]     = "#9266d7";
static const char purple4[]     = "#9266d7";
static const char purple5[]     = "#9266d7";
static const char purple6[]     = "#9266d7";
static const char purple7[]     = "#9266d7";
static const char purple8[]     = "#9266d7";
static const char purple9[]     = "#ba8eff";
/* static const char purple0[]     = "#9266d7"; */
/* static const char purple1[]     = "#976bdc"; */
/* static const char purple2[]     = "#9c70e1"; */
/* static const char purple3[]     = "#a175e6"; */
/* static const char purple4[]     = "#a67aeb"; */
/* static const char purple5[]     = "#ab7ff0"; */
/* static const char purple6[]     = "#b084f5"; */
/* static const char purple7[]     = "#b589fa"; */
/* static const char purple8[]     = "#ba8eff"; */
/* static const char col_borderbar[]  = "#1e222a"; // inner border */
/* static const char col_borderbar[]  = "#181c24"; // inner border */
static const char col_borderbar[]  = "#171b1f"; // inner border
